### ISSUE TITLE
连接报错啊

### ISSUE THREAD

**Issue by xudongxiao** [luxiaoxun/Code4Java#2]
java.io.IOException
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:348)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:603)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:625)
	at com.citicbank.itis.executor.netty.server.rabbitmq.server.MqReceiver$1.run(MqReceiver.java:43)
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:348)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:294)
	... 3 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:534)
	at java.lang.Thread.run(Thread.java:722)
10:47:16,913 ERROR MqReceiver:67 - Create Rabbit MQ listener error null

**Comment by luxiaoxun** [comment]
You must start a rabbitmq service first:
<rabbit:connection-factory id="connectionFactory" host="192.8.125.202" username="guest" password="guest" 
    port="5672" virtual-host="/" />
